[project]
name = "diy-smol-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.3.2",
    "ipykernel>=6.29.5",
    "torch>=2.6.0",
    "transformers>=4.49.0",
    "trl>=0.15.2",
]
